version: "3.9"

volumes:
  database_data:

networks:
  backend:
    name: backend

services:

  postgres_service:
    container_name: postgres
    image: postgres:14.1-alpine3.14
    restart: unless-stopped
    env_file:
      - docker/postgres/postgres.env
    ports: 
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - backend

  redis_service:
    container_name: redis
    image: redis:latest
    restart: unless-stopped
    ports: 
      - 6379:6379
    volumes:
      - database_data:/var/lib/redis/data
    networks:
      - backend
      

  nginx_service:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend_service
    networks:
      - backend


  backend_service:
    container_name: django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - docker/postgres/postgres.env
      - docker/django/django.env
      - docker/django/email.env
      - docker/redis/redis.env
    depends_on:
      - postgres_service
      - redis_service
    networks:
      - backend




  